name: hacker_news
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  async: ^2.11.0
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  provider: ^6.0.5
  share_plus: ^7.0.2
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.2.3
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
